CREATE TABLE LuanVan(
	MaLV VARCHAR(10) PRIMARY KEY,
	TenLV NVARCHAR(255) NOT NULL,
	NgayBD Date,
	NgayKT Date,
	TgBD Time,
	TgKT Time,
	ChuyenNganh VARCHAR(255),
	TrangThai VARCHAR(100),
	MoTaChiTiet NVARCHAR(255)
	
)

CREATE TABLE GiangVien(
	MaGV VARCHAR(10) PRIMARY KEY,
	TenGV NVARCHAR(255) NOT NULL,
	GioiTinh VARCHAR(10),
	DiaChi VARCHAR(255),
	CCCD VARCHAR(12),
	NgaySinh Date,
	SDT VARCHAR(11),
	Email VARCHAR(255)
)

CREATE TABLE SinhVien(
	MSSV VARCHAR(10) PRIMARY KEY,
	TenSV NVARCHAR(255) NOT NULL,
	GioiTinh VARCHAR(10),
	DiaChi VARCHAR(255),
	CCCD VARCHAR(12),
	NgaySinh Date,
	SDT VARCHAR(11),
	Email VARCHAR(255)
)




